In [1]:
import pandas as pd
import numpy as np

# a

In [2]:
df=pd.read_csv('Dataframe.csv')

In [3]:
df

    ID Name     Diet  Pulse  Time(min)     Kind
0    0    A  low fat     85         40  walking
1    1    A  low fat     85         45  walking
2    2    A   no fat     88         30  running
3    3    B   no fat     90         10  walking
4    4    B   no fat     92         15     rest
5    5    B  low fat     93         30     rest
6    6    C  low fat     97         15     rest
7    7    C  low fat     97         15     rest
8    8    C  low fat     94         30  walking
9    9    D  low fat     80         10  walking
10  10    D  low fat     82         15     rest
11  11    D  low fat     83         30     rest
12  12    E   no fat     91         10     rest
13  13    E  low fat     92         15  running
14  14    E  low fat     91         30  running

In [4]:
for i in df.Pulse:
    print(max(df.Pulse))

97
97
97
97
97
97
97
97
97
97
97
97
97
97
97

# b

In [5]:
result=0        
for i in df.Name:
    if(i.startswith('A') or i.startswith('B') and df['Diet'].equals('low fat')):
        result+=1
        
result

3

In [6]:
df.sort_index(ascending=False,axis=1)

    Time(min)  Pulse Name     Kind  ID     Diet
0          40     85    A  walking   0  low fat
1          45     85    A  walking   1  low fat
2          30     88    A  running   2   no fat
3          10     90    B  walking   3   no fat
4          15     92    B     rest   4   no fat
5          30     93    B     rest   5  low fat
6          15     97    C     rest   6  low fat
7          15     97    C     rest   7  low fat
8          30     94    C  walking   8  low fat
9          10     80    D  walking   9  low fat
10         15     82    D     rest  10  low fat
11         30     83    D     rest  11  low fat
12         10     91    E     rest  12   no fat
13         15     92    E  running  13  low fat
14         30     91    E  running  14  low fat